# Generated by Django 3.1 on 2020-10-27 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.CharField(choices=[('Report a bug', 'Report a bug'), ('Feature Request', 'Feature Request'), ('Enhancement', 'Enhancement')], default='Report a bug', max_length=100)),
                ('message', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ShortenUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_url', models.CharField(max_length=200)),
                ('short_url', models.CharField(max_length=30, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField()),
                ('expire_flag', models.BooleanField(default=False)),
                ('visits', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('click_datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('referrer_url', models.CharField(max_length=255)),
                ('clicks', models.IntegerField(default=0)),
                ('shorten_id', models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='mainApp.shortenurl')),
            ],
        ),
    ]
