# Generated by Django 3.1.7 on 2021-02-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenurl',
            name='user',
        ),
    ]
